FROM docker.n8n.io/n8nio/n8n:latest

ENV N8N_PORT=8080
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https
ENV N8N_RUNNERS_ENABLED=true
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

EXPOSE 8080

CMD ["n8n", "start"]
