FROM n8nio/n8n:latest

ENV N8N_PORT=8080
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin123
ENV GENERIC_TIMEZONE=Asia/Dubai
ENV TZ=Asia/Dubai

EXPOSE 8080
